config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  resources :users
  get '/login', to: 'users#signin'
  get '/register', to: 'users#signup'
  # Error routing
  get '/403', to: 'errors#permission_denied'
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'
  # Alternative error routes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :level, inclusion: { in: %w(user mooderator admin),
                                 message: "%{value} is not a valid user level" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def permission_denied
    render status: 403
  end

  def not_found
    render status: 404
  end

  def unacceptable
    render status: 422
  end

  def internal_error
    render status: 500
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def signin
  end

  def signup
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :pronouns, :description, :email,
                                   :level, :icon, :banner)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # https://gist.github.com/mynameispj/5692162
  def current_path?(test_path)
    return 'active' if request.path == test_path
    ''
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navigation.html.erb
      <nav>
        <%= link_to 'Login', login_path,
          class: current_path?(login_path) %>
        <%= link_to 'Register', register_path,
          class: current_path?(register_path) %>
      </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset='utf-8'/>
    <meta content='width=device-width, initial-scale=1' name='viewport'/>
    <%= favicon_link_tag %>
    <title>Moobooks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <h1>
        <%= link_to(
          image_tag('mootech_banner', size: "360x120", alt: "Mootech"), '/') %>
      </h1>
<%= render 'layouts/navigation' %>    </header>
    <main>
<%= yield %>    </main>
    <footer>
      <section id='art_copyright'>
        Artwork &copy; 2017
        <a href='https://www.furaffinity.net/user/ulvra' target='_blank'>
          Ulvra
        </a>
      </section>
      <section id='privacy_notice'>
        <a href='/terms_of_service/'> Terms of Service </a> |
        <a href='/privacy_policy/'> Privacy Policy </a>
      </section>
    </footer>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/signin.html.erb
      <section id='user_signin'>
        <h2> User signin </h2>
        <p> Please choose a social media platform to sign into
        Mootech with. </p>
      </section>

app/views/users/signup.html.erb
      <section id='user_signup'>
        <h2> User signup </h2>
        <p> Please choose a social media platform to register yourself with
        on Mootech. </p>
      </section>

app/views/welcome/index.html.erb
      <section id='welcome_index'>
        <h2> Welcome to Mootech </h2>
        <p> You are visiting Mootech, the place where Moo's invent new things
        and they <em class='stroke'>try to conquer the world</em> try to make
        people a little happier.</p>
        <p> What you are going to find here, are services of various kinds,
        but mostly ebook account services.</p>
      </section>